### ISSUE TITLE
Open Source Licensed?

### ISSUE THREAD

**Issue by hatzopoulos** [glafarge/ImagePlaceholder#2]
@glafarge 

Is this software licensed as open source, if so which specific license (MIT, GPL, Apache, etc)?

Would you consider adding a LICENSE file?

**Comment by hatzopoulos** [comment]
```
cd ~/Projects
git clone https://github.com/glafarge/ImagePlaceholder.git
cd ImagePlaceholder
php -S localhost:8000

PHP 7.3.9 Development Server started at Mon Oct 21 13:43:51 2019
Listening on http://localhost:8000
Document root is /Users/blackhole/Projects/ImagePlaceholder
Press Ctrl-C to quit.
[Mon Oct 21 13:44:06 2019] [::1]:52345 [200]: /300x300
[Mon Oct 21 13:44:06 2019] [::1]:52346 [404]: /favicon.ico - No such file or directory
```

![image](https://user-images.githubusercontent.com/1771931/67229237-e62aef80-f408-11e9-86e1-13bfca2e324b.png)

**Comment by glafarge** [comment]
Project no longer maintained but added LICENSE file in commit 9598fcb57e409dc8fc374472ae877b7c2a5adbde to FIX the issue ;)
